---
volumes:
  1pass-data: {}

services:
  api:
    image: 1password/connect-api:${_1PASS_CONNECT_VERSION}
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      - OP_LOG_LEVEL=info
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - 1pass-data:/home/opuser/.op/data

  sync:
    image: 1password/connect-sync:${_1PASS_CONNECT_VERSION}
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      - OP_LOG_LEVEL=info
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - 1pass-data:/home/opuser/.op/data
